config/routes.rb
Rails.application.routes.draw do
  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :forms
    end
  end
  get 'welcome/index'
  resources :forms
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/form.rb
class Form < ApplicationRecord
end

app/controllers/api/v1/forms_controller.rb
module Api
    module V1
        class FormsController < ApplicationController
            skip_before_action :verify_authenticity_token
            respond_to :json

            def index
                respond_with Form.all
            end

            def show
                respond_with Form.find(params[:id])
            end

            def create
                @form = Form.new(form_params)
                if @form.save
                    render json: {:status => 'Success', :object => @form}
                else
                    render json: {:status => 'Error', :object => @form}
                end
            end

            def update
                @form = Form.find(params[:id])
                if @form.update(form_params)
                    render json: {:status => 'Success', :object => @form}
                else
                    render json: {:status => 'Error', :object => @form}
                end
            end

            def destroy
                respond_with Form.destroy(params[:id])
            end
        private
            def form_params
                params.require(:form).permit(:title, :firstname, :lastname, :knownas, :q1, :q2, :q3, :q4, :q5, :info)
            end
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
    def index
        @forms = Form.all
    end

    def new
    end

    def create
        @form = Form.new(form_params)
        if @form.save
            redirect_to @form
        else
            render 'new'
        end
    end

    def show
        @form = Form.find(params[:id])
    end

    def edit
        @form = Form.find(params[:id])
    end

    def update
        @form = Form.find(params[:id])
        if @form.update(form_params)
            redirect_to @form
        else
            render 'edit'
        end
    end

    def destroy
        @form = Form.find(params[:id])
        @form.destroy

        redirect_to forms_path
    end

private
    def form_params
        params.require(:form).permit(:title, :firstname, :lastname, :knownas, :q1, :q2, :q3, :q4, :q5, :info)
    end
    
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/forms/edit.html.erb
<h1 class="text-center">Edit Submission  <%= @form.id %></h1>
<p> </p>


<%= form_with model: @form, local: true do |f| %>
    <p>
    <div class="form-group">
        <%= f.label :title, 'Title' %>
        <%= f.select(:title, ['Miss', 'Mrs', 'Ms', 'Master', 'Mr', 'Dr', 'Mx' ].sort, {:prompt => 'Please select option...'}, {:class => "form-control"}) %>
    </div>
    <div class="form-group">
        <%= f.label :firstname, 'First Name' %>
        <%= f.text_field(:firstname, {:class => "form-control"}) %>
    </div>
    <div class="form-group">
        <%= f.label :lastname, 'Last Name' %>
        <%= f.text_field(:lastname, {:class => "form-control"}) %>
    </div>
    <div class="form-group">
        <%= f.label :knownas, 'Known As' %>
        <%= f.text_field(:knownas, {:class => "form-control"}) %>
    </div>
    <div class="form-group">
        <%= f.label :q1, 'First very long question?' %>
        <%= f.select(:q1, ['option 1', 'option 2', 'option 3', 'option 4', 'option 5', ], {:prompt => 'Please select option...'}, {:class => "form-control"}) %>
    </div>
    <div class="form-group">
    <%= f.label :q2, 'Second very long question?' %>
    <%= f.select(:q2, ['option 1', 'option 2', 'option 3', 'option 4', 'option 5', ], {:prompt => 'Please select option...'}, {:class => "form-control"}) %>
    </div>
        <div class="form-group">
        <%= f.label :q3, 'First very long question?' %>
        <%= f.select(:q3, ['option 1', 'option 2', 'option 3', 'option 4', 'option 5', ], {:prompt => 'Please select option...'}, {:class => "form-control"}) %>
    </div>
    <div class="form-group">
        <%= f.label :q4, 'First very long question?' %>
        <%= f.select(:q4, ['option 1', 'option 2', 'option 3', 'option 4', 'option 5', ], {:prompt => 'Please select option...'}, {:class => "form-control"}) %>
    </div>
    <div class="form-group">
        <%= f.label :q5, 'First very long question?' %>
        <%= f.select(:q5, ['option 1', 'option 2', 'option 3', 'option 4', 'option 5', ], {:prompt => 'Please select option...'}, {:class => "form-control"}) %>
    </div>
    <div class="form-group">
        <%= f.label :info, 'Any aditional information?' %>
        <%= f.text_area(:info, {:class => "form-control"}) %>
    </div>

    <div class="form-group float-right">
        <%= f.submit 'Save', :class => 'btn btn-primary' %>
    </div>
<% end %>

app/views/forms/index.html.erb
<h1 class="text-center">All Forms</h1>

<div class="alert alert-info" role="alert">
    Total of <strong><%= @forms.count %></strong> records</h3>
</div>

<% @forms.each do |form| %>
    <div class="modal fade" id="deleteModal<%= form.id %>" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel<%= form.id %>" aria-hidden="false">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModal<%= form.id %>">
                        Delete Record <%= form.id %>
                    </h5> 
                    <button type="button" class="close" data-dismiss="modal">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">
                    Are you sure you want to remove this record?
                    <p></p>
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>Question</th>
                                <th>Answer</th>
                            </tr>
                        </thead>
                        <tbody>
	                    <tr>
			                <td>Title</td>
			                <td><%= form.title %></td>
                        </tr>
	                    <tr>
			                <td>First Name</td>
			                <td><%= form.firstname %></td>
                        </tr>
	                    <tr>
                            <td>Last Name</td>
			                <td><%= form.lastname %></td>
                        </tr>
	                    <tr>
			                <td>Known As</td>
			                <td><%= form.knownas %></td>
                        </tr>
	                    <tr>
			                <td>Question 1</td>
			                <td><%= form.q1 %></td>
                        </tr>
	                    <tr>
			                <td>Question 2</td>
			                <td><%= form.q2 %></td>
                        </tr>
                        <tr>
			                <td>Question 3</td>
			                <td><%= form.q3 %></td>
                        </tr>
	                    <tr>
                            <td>Question 4</td>
                            <td><%= form.q4 %></td>
                        </tr>
                        <tr>
                            <td>Question 5</td>
			                <td><%= form.q5 %></td>
                        </tr>
	                    <tr>
			                <td>Info</td>
			                <td><%= form.info %></td>
                        </tr>
	                    <tr>
			                <td>Created</td>
			                <td><%= form.created_at.to_formatted_s(:long_ordinal) %></td>
                        </tr>
	                    <tr>
			                <td>Updated</td>
			                <td><%= form.updated_at.to_formatted_s(:long_ordinal) %></td>
                        </tr>
	                    </tbody>
                    </table>
                    
                </div>
                <div class="modal-footer">
                    <%= button_to "Delete", form_path(form), method: :delete, :class => "btn btn-danger" %>
                </div>
            </div>	
        </div>
    </div>
<% end %>

<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Info</th>
            <th>Updated</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    </th>

    <% @forms.each do |form| %>
        <tr>
            <td><%= link_to form.id, form_path(form), method: :get %></td>
            <td><%= form.firstname.capitalize %></td>
            <td><%= form.lastname.capitalize %></td>
            <td><%= form.info.first(100) %></td>
            <td><%= form.updated_at.to_formatted_s(:long_ordinal) %></td>
            <td><%= button_to "Edit", edit_form_path(form), method: :get, :class => "btn btn-primary" %></td>
            <td><button type="button" class="btn btn-danger" data-toggle="modal" data-target="#deleteModal<%= form.id %>">Delete</button></td>
        </tr>
    <% end %>

</table>

app/views/forms/new.html.erb
<h1 class="text-center">New Submission</h1>
<p> </p>
<div class="alert alert-dismissable alert-info">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
        ×
    </button>
    <h4 class="text-center">Start</h4>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
</div>

<p></p>

<%= form_with scope: :form, url: forms_path, local: true do |f| %>
    <p>
    <div class="form-group">
        <%= f.label :title, 'Title' %>
        <%= f.select(:title, ['Miss', 'Mrs', 'Ms', 'Master', 'Mr', 'Dr', 'Mx' ].sort, {:prompt => 'Please select option...'}, {:class => "form-control"}) %>
    </div>
    <div class="form-group">
        <%= f.label :firstname, 'First Name' %>
        <%= f.text_field(:firstname, {:class => "form-control"}) %>
    </div>
    <div class="form-group">
        <%= f.label :lastname, 'Last Name' %>
        <%= f.text_field(:lastname, {:class => "form-control"}) %>
    </div>
    <div class="form-group">
        <%= f.label :knownas, 'Known As' %>
        <%= f.text_field(:knownas, {:class => "form-control"}) %>
    </div>
    <div class="form-group">
        <%= f.label :q1, 'First very long question?' %>
        <%= f.select(:q1, ['option 1', 'option 2', 'option 3', 'option 4', 'option 5', ], {:prompt => 'Please select option...'}, {:class => "form-control"}) %>
    </div>
    <div class="form-group">
    <%= f.label :q2, 'Second very long question?' %>
    <%= f.select(:q2, ['option 1', 'option 2', 'option 3', 'option 4', 'option 5', ], {:prompt => 'Please select option...'}, {:class => "form-control"}) %>
    </div>
        <div class="form-group">
        <%= f.label :q3, 'First very long question?' %>
        <%= f.select(:q3, ['option 1', 'option 2', 'option 3', 'option 4', 'option 5', ], {:prompt => 'Please select option...'}, {:class => "form-control"}) %>
    </div>
    <div class="form-group">
        <%= f.label :q4, 'First very long question?' %>
        <%= f.select(:q4, ['option 1', 'option 2', 'option 3', 'option 4', 'option 5', ], {:prompt => 'Please select option...'}, {:class => "form-control"}) %>
    </div>
    <div class="form-group">
        <%= f.label :q5, 'First very long question?' %>
        <%= f.select(:q5, ['option 1', 'option 2', 'option 3', 'option 4', 'option 5', ], {:prompt => 'Please select option...'}, {:class => "form-control"}) %>
    </div>
    <div class="form-group">
        <%= f.label :info, 'Any aditional information?' %>
        <%= f.text_area(:info, {:class => "form-control"}) %>
    </div>

    <div class="form-group float-right">
        <%= f.submit 'Continue', :class => 'btn btn-primary' %>
    </div>
<% end %>

app/views/forms/show.html.erb
<h1 class="text-center">Form <%= @form.id %></h1>


<table class="table table-hover">
    <thead>
        <tr>
            <th>
                Question
			</th>
            <th>
                Answer
            </th>
    </thead>
    <tbody>
	    <tr>
			<td>
                Title
			</td>
			<td>
                <%= @form.title %>
            </td>
        </tr>
	    <tr>
			<td>
                First Name
			</td>
			<td>
                <%= @form.firstname %>
            </td>
        </tr>
	    <tr>
			<td>
                Last Name
			</td>
			<td>
                <%= @form.lastname %>
            </td>
        </tr>
	    <tr>
			<td>
                Known As
			</td>
			<td>
                <%= @form.knownas %>
            </td>
        </tr>
	    <tr>
			<td>
                Question 1
			</td>
			<td>
                <%= @form.q1 %>
            </td>
        </tr>
	    <tr>
			<td>
                Question 2
			</td>
			<td>
                <%= @form.q2 %>
            </td>
        </tr>
	    <tr>
			<td>
                Question 3
			</td>
			<td>
                <%= @form.q3 %>
            </td>
        </tr>
	    <tr>
			<td>
                Question 4
			</td>
			<td>
                <%= @form.q4 %>
            </td>
        </tr>
	    <tr>
			<td>
                Question 5
			</td>
			<td>
                <%= @form.q5 %>
            </td>
        </tr>
	    <tr>
			<td>
                Info
			</td>
			<td>
                <%= @form.info %>
            </td>
        </tr>
	    <tr>
			<td>
                Created
			</td>
			<td>
                <%= @form.created_at.to_formatted_s(:long_ordinal) %>
            </td>
        </tr>
	    <tr>
			<td>
                Updated
			</td>
			<td>
                <%= @form.updated_at.to_formatted_s(:long_ordinal) %>
            </td>
        </tr>
	</tbody>
</table>
<p></p>
<p><%= button_to "Edit", edit_form_path(@form), method: :get, :class => "btn btn-primary float-right" %></p>
<p></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestRails</title>
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

	<div class="container-float">
		<div class="row">
			<div class="col-md-12 text-white">
				<nav class="navbar navbar-dark bg-primary"> 
					<a class="navbar-brand" href="/">Test Rails</a>
						<ul class="navbar-nav">
							<li class="nav-item active">
							 	<a class="nav-link" href="/forms">All Forms</a>
							</li>
						</ul>
						<ul class="navbar-nav ml-md-auto">
							<li class="nav-item active">
								 <a class="nav-link" href="https://gitlab.com"><i class="fab fa-gitlab"></i> Source</a>
							</li>
						</ul>
				</nav>
			</div>
		</div>
	</div>
	<div class="container-float ">
		<div class="row">
       		<div class="col-md-2 bg-primary">
        	</div>
        	<div class="col-md-8 bg-light">
          		<%= yield %>
        	</div>
			<div class="col-md-2 bg-primary">
			</div>
		</div>
	</div>
	<div class="container-float text-center text-md-left">
		<footer class="page-footer font-small bg-primary text-white">
			<div class="footer-copyright text-center py-3">Test Rails App
			</div>
		</footer>
	</div>
  </body>
</html>

app/views/welcome/index.html.erb
<h1 class="text-center">Simple Test App</h1>

<p></p>
<div class="jumbotron">
    <h3>Description</h3>
    <p>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </p>
    <p>
        <a class="btn btn-primary btn-large" href="forms/new">Start Now</a>
    </p>
</div>